'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const { parseMO2, parseModlist, diffRows, buildRows, csvCell, formatSize, matchesQuery } = require('./extract.js');

const NL = '\n';
const mo2 = (...lines) => lines.join(NL);

// ---------------------------------------------------------------- parseMO2

test('parseMO2: markers set enabled state', () => {
  const e = parseMO2(mo2('+On', '-Off', '*Unmanaged'));
  assert.deepStrictEqual(e.map((x) => [x.name, x.enabled, x.unmanaged]), [
    ['On', true, false],
    ['Off', false, false],
    ['Unmanaged', true, true],
  ]);
});

test('parseMO2: comments, blanks and unmarked lines are skipped', () => {
  const e = parseMO2(mo2('# generated by Mod Organizer', '', '   ', 'no marker here', '+Real'));
  assert.deepStrictEqual(e.map((x) => x.name), ['Real']);
});

test('parseMO2: names are trimmed', () => {
  assert.strictEqual(parseMO2('+   Spaced Name   ')[0].name, 'Spaced Name');
});

test('parseMO2: CRLF files parse identically to LF', () => {
  const lines = ['# gen', '+A', '-B'];
  assert.deepStrictEqual(parseMO2(lines.join('\r\n')), parseMO2(lines.join('\n')));
});

test('parseMO2: separators are excluded but still consume a file position', () => {
  // Separators occupy a slot in MO2's pane, so dropping their position would
  // shift every mod below them.
  const e = parseMO2(mo2('+First', '+Section_separator', '+Second'));
  assert.deepStrictEqual(e.map((x) => x.name), ['First', 'Second']);
  assert.deepStrictEqual(e.map((x) => x.filePosition), [0, 2]);
});

test('parseMO2: empty input yields no entries', () => {
  assert.deepStrictEqual(parseMO2(''), []);
});

// ------------------------------------------------------------ parseModlist

test('parseModlist: detects a Vortex state file', () => {
  const res = parseModlist(JSON.stringify({ persistent: { mods: { skyrimse: { a: {} } }, profiles: {} } }));
  assert.strictEqual(res.source.type, 'vortex');
});

test('parseModlist: accepts an unwrapped Vortex backup', () => {
  // Some backups are stored without the `persistent` wrapper.
  const res = parseModlist(JSON.stringify({ mods: { skyrimse: { a: {} } }, profiles: {} }));
  assert.strictEqual(res.source.type, 'vortex');
});

test('parseModlist: detects an MO2 modlist', () => {
  assert.strictEqual(parseModlist(mo2('# gen', '+A')).source.type, 'mo2');
});

test('parseModlist: JSON with no mods is rejected with the keys it did contain', () => {
  const res = parseModlist(JSON.stringify({ settings: 1, window: 2 }));
  assert.ok(res.error);
  assert.match(res.error, /settings, window/);
});

test('parseModlist: truncated JSON is reported as truncated, not as the wrong file', () => {
  const res = parseModlist('{"persistent":{"mods":{"skyrimse":{"a":{"attribu');
  assert.ok(res.error);
  assert.match(res.error, /truncated|mid-save/);
});

test('parseModlist: unrecognised text is rejected', () => {
  const res = parseModlist('just some notes' + NL + 'nothing structured');
  assert.ok(res.error);
  assert.match(res.error, /Couldn't recognize/);
});

// ------------------------------------------------------- buildRows: Vortex

const vortex = (mods, profiles) => ({ type: 'vortex', mods: { skyrimse: mods }, profiles: profiles || {} });

test('buildRows: name falls back through the attribute chain', () => {
  const rows = buildRows(vortex({
    a: { attributes: { customFileName: 'Custom', name: 'Name' } },
    b: { attributes: { name: 'Name' } },
    c: { attributes: { logicalFileName: 'Logical' } },
    d: { attributes: {} },
  }), 'skyrimse', '__all__');
  const byId = Object.fromEntries(rows.map((r) => [r.modId, r.name]));
  assert.deepStrictEqual(byId, { a: 'Custom', b: 'Name', c: 'Logical', d: 'd' });
});

test('buildRows: a Nexus mod links to its mod page', () => {
  const [row] = buildRows(vortex({ a: { attributes: { name: 'A', source: 'nexus', modId: 6276 } } }), 'skyrimse', '__all__');
  assert.strictEqual(row.sourceUrl, 'https://www.nexusmods.com/skyrimse/mods/6276');
});

test('buildRows: a non-numeric modId does not produce a link', () => {
  const [row] = buildRows(vortex({ a: { attributes: { name: 'A', source: 'nexus', modId: '1 onmouseover=alert(1)' } } }), 'skyrimse', '__all__');
  assert.strictEqual(row.sourceUrl, null);
});

test('buildRows: a collection links to the collection page and is labelled', () => {
  const [row] = buildRows(vortex({
    c: { type: 'collection', attributes: { name: 'Coll', source: 'nexus', collectionSlug: 'n0nymh', downloadGame: 'cyberpunk2077' } },
  }), 'skyrimse', '__all__');
  assert.strictEqual(row.source, 'collection');
  assert.strictEqual(row.sourceUrl, 'https://www.nexusmods.com/games/cyberpunk2077/collections/n0nymh');
});

test('buildRows: a collection slug containing path traversal is not linked', () => {
  const [row] = buildRows(vortex({
    c: { type: 'collection', attributes: { name: 'Sketchy', collectionSlug: 'evil/../../x', downloadGame: 'cyberpunk2077' } },
  }), 'skyrimse', '__all__');
  assert.strictEqual(row.source, 'collection');
  assert.strictEqual(row.sourceUrl, null);
});

test('buildRows: enabled is null without a profile and boolean with one', () => {
  const mods = { a: { attributes: { name: 'A' } } };
  const profiles = { p1: { gameId: 'skyrimse', name: 'Main', modState: { a: { enabled: false } } } };
  assert.strictEqual(buildRows(vortex(mods, profiles), 'skyrimse', '__all__')[0].enabled, null);
  assert.strictEqual(buildRows(vortex(mods, profiles), 'skyrimse', 'p1')[0].enabled, false);
});

test('buildRows: an unknown game yields no rows rather than throwing', () => {
  assert.deepStrictEqual(buildRows(vortex({ a: { attributes: {} } }), 'nosuchgame', '__all__'), []);
});

// ---------------------------------------------------------- buildRows: MO2

test('buildRows: MO2 order is the reverse of file order', () => {
  // VERIFIED against a real profile: modlist.txt is written bottom-to-top
  // relative to MO2's pane, so the last line is the top of the pane.
  const source = { type: 'mo2', entries: parseMO2(mo2('+Bottom', '+Middle', '+Top')) };
  const rows = buildRows(source, null, null);
  const rank = Object.fromEntries(rows.map((r) => [r.name, r.order]));
  assert.deepStrictEqual(rank, { Top: 1, Middle: 2, Bottom: 3 });
});

test('buildRows: a separator consumes a rank without appearing', () => {
  const source = { type: 'mo2', entries: parseMO2(mo2('+Bottom', '+Sep_separator', '+Top')) };
  const rows = buildRows(source, null, null);
  assert.deepStrictEqual(rows.map((r) => r.name).sort(), ['Bottom', 'Top']);
  assert.deepStrictEqual(Object.fromEntries(rows.map((r) => [r.name, r.order])), { Top: 1, Bottom: 2 });
});

// ----------------------------------------------------------------- diffRows

const R = (modId, extra) => Object.assign({ modId, name: modId, version: '1.0', enabled: true }, extra);

test('diffRows: classifies added, removed, changed and unchanged', () => {
  const d = diffRows(
    [R('Same'), R('Bumped'), R('Dropped')],
    [R('Same'), R('Bumped', { version: '2.0' }), R('Fresh')]
  );
  const by = Object.fromEntries(d.map((x) => [x.row.modId, x.change]));
  assert.deepStrictEqual(by, { Same: 'unchanged', Bumped: 'changed', Dropped: 'removed', Fresh: 'added' });
});

test('diffRows: records from/to for version, status and order', () => {
  const [d] = diffRows(
    [R('M', { version: '1.0', enabled: true, order: 5 })],
    [R('M', { version: '2.0', enabled: false, order: 1 })]
  );
  assert.deepStrictEqual(
    d.changes.map((c) => [c.field, String(c.from), String(c.to)]).sort(),
    [['order', '5', '1'], ['status', 'enabled', 'disabled'], ['version', '1.0', '2.0']].sort()
  );
});

test('diffRows: an unknown status on either side is not a change', () => {
  // Vortex keeps enabled state on the profile. When the selected profile is
  // absent from the other file that side falls back to its full installed
  // list, where status is unknown. Treating unknown as a change marked every
  // single mod as modified.
  assert.strictEqual(diffRows([R('M', { enabled: true })], [R('M', { enabled: null })])[0].change, 'unchanged');
  assert.strictEqual(diffRows([R('M', { enabled: null })], [R('M', { enabled: true })])[0].change, 'unchanged');
});

test('diffRows: a real status flip is still reported', () => {
  const [d] = diffRows([R('M', { enabled: true })], [R('M', { enabled: false })]);
  assert.strictEqual(d.changes[0].field, 'status');
});

test('diffRows: a removed entry carries the old row', () => {
  const [d] = diffRows([R('Gone', { version: '9.9' })], []);
  assert.strictEqual(d.change, 'removed');
  assert.strictEqual(d.row.version, '9.9');
});

test('diffRows: groups added, removed, changed, unchanged in that order', () => {
  const d = diffRows([R('Keep'), R('Old')], [R('Keep'), R('New')]);
  const rank = { added: 0, removed: 1, changed: 2, unchanged: 3 };
  const seen = d.map((x) => rank[x.change]);
  assert.deepStrictEqual(seen, [...seen].sort((a, b) => a - b));
});

test('diffRows: empty inputs', () => {
  assert.deepStrictEqual(diffRows([], []), []);
  assert.strictEqual(diffRows([], [R('A')])[0].change, 'added');
  assert.strictEqual(diffRows([R('A')], [])[0].change, 'removed');
});

// ------------------------------------------------------------------ csvCell

test('csvCell: quotes are doubled', () => {
  assert.strictEqual(csvCell('say "hi"'), '"say ""hi"""');
});

test('csvCell: formula-leading characters are neutralised', () => {
  // Mod names are written by mod authors and end up in a spreadsheet.
  for (const lead of ['=', '+', '-', '@']) {
    assert.strictEqual(csvCell(lead + 'cmd|calc'), '"\'' + lead + 'cmd|calc"');
  }
});

test('csvCell: ordinary values are untouched', () => {
  assert.strictEqual(csvCell('Normal Mod'), '"Normal Mod"');
});

// --------------------------------------------------------------- formatSize

test('formatSize: scales through units', () => {
  assert.strictEqual(formatSize(512), '512 B');
  assert.strictEqual(formatSize(1024), '1.0 KB');
  assert.strictEqual(formatSize(5 * 1024 * 1024), '5.0 MB');
  assert.strictEqual(formatSize(2.5 * 1024 * 1024 * 1024), '2.5 GB');
});

test('formatSize: drops the decimal once the number is big enough to not need it', () => {
  assert.strictEqual(formatSize(150 * 1024 * 1024), '150 MB');
});

test('formatSize: missing or nonsensical sizes render as a dash', () => {
  for (const v of [null, undefined, 0, -1, NaN, Infinity, '900']) {
    assert.strictEqual(formatSize(v), '—', 'failed for ' + String(v));
  }
});

// ------------------------------------------------------------- matchesQuery

const row = { name: 'Unofficial Skyrim Patch', modId: 'USSEP-266', version: '4.3.2', source: 'nexus' };

test('matchesQuery: an empty query matches everything', () => {
  for (const q of ['', '   ', null, undefined]) assert.strictEqual(matchesQuery(row, q), true);
});

test('matchesQuery: case-insensitive substring over name, id, version and source', () => {
  assert.strictEqual(matchesQuery(row, 'skyrim'), true);
  assert.strictEqual(matchesQuery(row, 'SKYRIM'), true);
  assert.strictEqual(matchesQuery(row, 'ussep'), true);
  assert.strictEqual(matchesQuery(row, '4.3'), true);
  assert.strictEqual(matchesQuery(row, 'nexus'), true);
  assert.strictEqual(matchesQuery(row, 'morrowind'), false);
});

test('matchesQuery: multiple terms all have to match, in any order', () => {
  assert.strictEqual(matchesQuery(row, 'unofficial patch'), true);
  assert.strictEqual(matchesQuery(row, 'patch unofficial'), true);
  assert.strictEqual(matchesQuery(row, 'unofficial morrowind'), false);
});

test('matchesQuery: surrounding whitespace is ignored', () => {
  assert.strictEqual(matchesQuery(row, '  skyrim  '), true);
});

test('matchesQuery: tolerates rows with missing fields', () => {
  assert.strictEqual(matchesQuery({ name: 'Solo' }, 'solo'), true);
  assert.strictEqual(matchesQuery({ name: 'Solo' }, 'nexus'), false);
});

// ------------------------------------------------- buildRows: size plumbing

test('buildRows: modSize is preferred over fileSize, and absence is null', () => {
  const rows = buildRows(vortex({
    both: { attributes: { name: 'Both', modSize: 100, fileSize: 999 } },
    only: { attributes: { name: 'Only', fileSize: 42 } },
    none: { attributes: { name: 'None' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.size]));
  assert.deepStrictEqual(by, { Both: 100, Only: 42, None: null });
});

// -------------------------------------------------- optional: real backups

const backupDir = process.env.APPDATA
  ? path.join(process.env.APPDATA, 'Vortex', 'temp', 'state_backups_full')
  : null;
const realBackups = backupDir && fs.existsSync(backupDir)
  ? fs.readdirSync(backupDir).filter((f) => f.endsWith('.json')).map((f) => path.join(backupDir, f))
  : [];

test('real Vortex backups on this machine parse and diff', {
  skip: realBackups.length < 2 ? 'needs two local Vortex state backups; none committed to the repo' : false,
}, () => {
  const sources = realBackups.slice(0, 2).map((f) => {
    const res = parseModlist(fs.readFileSync(f, 'utf8'));
    assert.ok(!res.error, 'failed to parse ' + path.basename(f) + ': ' + res.error);
    assert.strictEqual(res.source.type, 'vortex');
    return res.source;
  });

  const games = Object.keys(sources[0].mods);
  assert.ok(games.length > 0, 'expected at least one game in a real backup');

  for (const game of games) {
    const a = buildRows(sources[0], game, '__all__');
    const b = buildRows(sources[1], game, '__all__');
    for (const row of a.concat(b)) {
      assert.ok(typeof row.name === 'string' && row.name.length > 0, 'every row needs a name');
      if (row.sourceUrl) {
        assert.match(row.sourceUrl, /^https:\/\/www\.nexusmods\.com\//, 'links must point at nexusmods.com');
      }
    }
    // Must not throw, and must account for every mod on both sides.
    const d = diffRows(a, b);
    const ids = new Set(a.concat(b).map((r) => r.modId));
    assert.strictEqual(d.length, ids.size);
  }
});
