'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const { parseMO2, parseModlist, diffRows, buildRows, csvCell, formatSize, matchesQuery,
        collectionMembership, collectionLabel, viewState,
        missingCollectionMembers, endorsementLabel, isUnendorsed } = require('./extract.js');

const NL = '\n';
const mo2 = (...lines) => lines.join(NL);

// ---------------------------------------------------------------- parseMO2

test('parseMO2: markers set enabled state', () => {
  const e = parseMO2(mo2('+On', '-Off', '*Unmanaged'));
  assert.deepStrictEqual(e.map((x) => [x.name, x.enabled, x.unmanaged]), [
    ['On', true, false],
    ['Off', false, false],
    ['Unmanaged', true, true],
  ]);
});

test('parseMO2: comments, blanks and unmarked lines are skipped', () => {
  const e = parseMO2(mo2('# generated by Mod Organizer', '', '   ', 'no marker here', '+Real'));
  assert.deepStrictEqual(e.map((x) => x.name), ['Real']);
});

test('parseMO2: names are trimmed', () => {
  assert.strictEqual(parseMO2('+   Spaced Name   ')[0].name, 'Spaced Name');
});

test('parseMO2: CRLF files parse identically to LF', () => {
  const lines = ['# gen', '+A', '-B'];
  assert.deepStrictEqual(parseMO2(lines.join('\r\n')), parseMO2(lines.join('\n')));
});

test('parseMO2: separators are excluded but still consume a file position', () => {
  // Separators occupy a slot in MO2's pane, so dropping their position would
  // shift every mod below them.
  const e = parseMO2(mo2('+First', '+Section_separator', '+Second'));
  assert.deepStrictEqual(e.map((x) => x.name), ['First', 'Second']);
  assert.deepStrictEqual(e.map((x) => x.filePosition), [0, 2]);
});

test('parseMO2: empty input yields no entries', () => {
  assert.deepStrictEqual(parseMO2(''), []);
});

// ------------------------------------------------------------ parseModlist

test('parseModlist: detects a Vortex state file', () => {
  const res = parseModlist(JSON.stringify({ persistent: { mods: { skyrimse: { a: {} } }, profiles: {} } }));
  assert.strictEqual(res.source.type, 'vortex');
});

test('parseModlist: accepts an unwrapped Vortex backup', () => {
  // Some backups are stored without the `persistent` wrapper.
  const res = parseModlist(JSON.stringify({ mods: { skyrimse: { a: {} } }, profiles: {} }));
  assert.strictEqual(res.source.type, 'vortex');
});

test('parseModlist: detects an MO2 modlist', () => {
  assert.strictEqual(parseModlist(mo2('# gen', '+A')).source.type, 'mo2');
});

test('parseModlist: JSON with no mods is rejected with the keys it did contain', () => {
  const res = parseModlist(JSON.stringify({ settings: 1, window: 2 }));
  assert.ok(res.error);
  assert.match(res.error, /settings, window/);
});

test('parseModlist: truncated JSON is reported as truncated, not as the wrong file', () => {
  const res = parseModlist('{"persistent":{"mods":{"skyrimse":{"a":{"attribu');
  assert.ok(res.error);
  assert.match(res.error, /truncated|mid-save/);
});

test('parseModlist: unrecognised text is rejected', () => {
  const res = parseModlist('just some notes' + NL + 'nothing structured');
  assert.ok(res.error);
  assert.match(res.error, /Couldn't recognize/);
});

// ------------------------------------------------------- buildRows: Vortex

const vortex = (mods, profiles) => ({ type: 'vortex', mods: { skyrimse: mods }, profiles: profiles || {} });

test('buildRows: name falls back through the attribute chain', () => {
  const rows = buildRows(vortex({
    a: { attributes: { customFileName: 'Custom', name: 'Name' } },
    b: { attributes: { name: 'Name' } },
    c: { attributes: { logicalFileName: 'Logical' } },
    d: { attributes: {} },
  }), 'skyrimse', '__all__');
  const byId = Object.fromEntries(rows.map((r) => [r.modId, r.name]));
  assert.deepStrictEqual(byId, { a: 'Custom', b: 'Name', c: 'Logical', d: 'd' });
});

test('buildRows: a Nexus mod links to its mod page', () => {
  const [row] = buildRows(vortex({ a: { attributes: { name: 'A', source: 'nexus', modId: 6276 } } }), 'skyrimse', '__all__');
  assert.strictEqual(row.sourceUrl, 'https://www.nexusmods.com/skyrimse/mods/6276');
});

test('buildRows: a non-numeric modId does not produce a link', () => {
  const [row] = buildRows(vortex({ a: { attributes: { name: 'A', source: 'nexus', modId: '1 onmouseover=alert(1)' } } }), 'skyrimse', '__all__');
  assert.strictEqual(row.sourceUrl, null);
});

test('buildRows: a collection links to the collection page and is labelled', () => {
  const [row] = buildRows(vortex({
    c: { type: 'collection', attributes: { name: 'Coll', source: 'nexus', collectionSlug: 'n0nymh', downloadGame: 'cyberpunk2077' } },
  }), 'skyrimse', '__all__');
  assert.strictEqual(row.source, 'collection');
  assert.strictEqual(row.sourceUrl, 'https://www.nexusmods.com/games/cyberpunk2077/collections/n0nymh');
});

test('buildRows: a collection slug containing path traversal is not linked', () => {
  const [row] = buildRows(vortex({
    c: { type: 'collection', attributes: { name: 'Sketchy', collectionSlug: 'evil/../../x', downloadGame: 'cyberpunk2077' } },
  }), 'skyrimse', '__all__');
  assert.strictEqual(row.source, 'collection');
  assert.strictEqual(row.sourceUrl, null);
});

test('buildRows: enabled is null without a profile and boolean with one', () => {
  const mods = { a: { attributes: { name: 'A' } } };
  const profiles = { p1: { gameId: 'skyrimse', name: 'Main', modState: { a: { enabled: false } } } };
  assert.strictEqual(buildRows(vortex(mods, profiles), 'skyrimse', '__all__')[0].enabled, null);
  assert.strictEqual(buildRows(vortex(mods, profiles), 'skyrimse', 'p1')[0].enabled, false);
});

test('buildRows: an unknown game yields no rows rather than throwing', () => {
  assert.deepStrictEqual(buildRows(vortex({ a: { attributes: {} } }), 'nosuchgame', '__all__'), []);
});

// ---------------------------------------------------------- buildRows: MO2

test('buildRows: MO2 order is the reverse of file order', () => {
  // VERIFIED against a real profile: modlist.txt is written bottom-to-top
  // relative to MO2's pane, so the last line is the top of the pane.
  const source = { type: 'mo2', entries: parseMO2(mo2('+Bottom', '+Middle', '+Top')) };
  const rows = buildRows(source, null, null);
  const rank = Object.fromEntries(rows.map((r) => [r.name, r.order]));
  assert.deepStrictEqual(rank, { Top: 1, Middle: 2, Bottom: 3 });
});

test('buildRows: a separator consumes a rank without appearing', () => {
  const source = { type: 'mo2', entries: parseMO2(mo2('+Bottom', '+Sep_separator', '+Top')) };
  const rows = buildRows(source, null, null);
  assert.deepStrictEqual(rows.map((r) => r.name).sort(), ['Bottom', 'Top']);
  assert.deepStrictEqual(Object.fromEntries(rows.map((r) => [r.name, r.order])), { Top: 1, Bottom: 2 });
});

// ----------------------------------------------------------------- diffRows

const R = (modId, extra) => Object.assign({ modId, name: modId, version: '1.0', enabled: true }, extra);

test('diffRows: classifies added, removed, changed and unchanged', () => {
  const d = diffRows(
    [R('Same'), R('Bumped'), R('Dropped')],
    [R('Same'), R('Bumped', { version: '2.0' }), R('Fresh')]
  );
  const by = Object.fromEntries(d.map((x) => [x.row.modId, x.change]));
  assert.deepStrictEqual(by, { Same: 'unchanged', Bumped: 'changed', Dropped: 'removed', Fresh: 'added' });
});

test('diffRows: records from/to for version, status and order', () => {
  const [d] = diffRows(
    [R('M', { version: '1.0', enabled: true, order: 5 })],
    [R('M', { version: '2.0', enabled: false, order: 1 })]
  );
  assert.deepStrictEqual(
    d.changes.map((c) => [c.field, String(c.from), String(c.to)]).sort(),
    [['order', '5', '1'], ['status', 'enabled', 'disabled'], ['version', '1.0', '2.0']].sort()
  );
});

test('diffRows: an unknown status on either side is not a change', () => {
  // Vortex keeps enabled state on the profile. When the selected profile is
  // absent from the other file that side falls back to its full installed
  // list, where status is unknown. Treating unknown as a change marked every
  // single mod as modified.
  assert.strictEqual(diffRows([R('M', { enabled: true })], [R('M', { enabled: null })])[0].change, 'unchanged');
  assert.strictEqual(diffRows([R('M', { enabled: null })], [R('M', { enabled: true })])[0].change, 'unchanged');
});

test('diffRows: a real status flip is still reported', () => {
  const [d] = diffRows([R('M', { enabled: true })], [R('M', { enabled: false })]);
  assert.strictEqual(d.changes[0].field, 'status');
});

test('diffRows: a removed entry carries the old row', () => {
  const [d] = diffRows([R('Gone', { version: '9.9' })], []);
  assert.strictEqual(d.change, 'removed');
  assert.strictEqual(d.row.version, '9.9');
});

test('diffRows: groups added, removed, changed, unchanged in that order', () => {
  const d = diffRows([R('Keep'), R('Old')], [R('Keep'), R('New')]);
  const rank = { added: 0, removed: 1, changed: 2, unchanged: 3 };
  const seen = d.map((x) => rank[x.change]);
  assert.deepStrictEqual(seen, [...seen].sort((a, b) => a - b));
});

test('diffRows: empty inputs', () => {
  assert.deepStrictEqual(diffRows([], []), []);
  assert.strictEqual(diffRows([], [R('A')])[0].change, 'added');
  assert.strictEqual(diffRows([R('A')], [])[0].change, 'removed');
});

// ------------------------------------------------------------------ csvCell

test('csvCell: quotes are doubled', () => {
  assert.strictEqual(csvCell('say "hi"'), '"say ""hi"""');
});

test('csvCell: formula-leading characters are neutralised', () => {
  // Mod names are written by mod authors and end up in a spreadsheet.
  for (const lead of ['=', '+', '-', '@']) {
    assert.strictEqual(csvCell(lead + 'cmd|calc'), '"\'' + lead + 'cmd|calc"');
  }
});

test('csvCell: ordinary values are untouched', () => {
  assert.strictEqual(csvCell('Normal Mod'), '"Normal Mod"');
});

// --------------------------------------------------------------- formatSize

test('formatSize: scales through units', () => {
  assert.strictEqual(formatSize(512), '512 B');
  assert.strictEqual(formatSize(1024), '1.0 KB');
  assert.strictEqual(formatSize(5 * 1024 * 1024), '5.0 MB');
  assert.strictEqual(formatSize(2.5 * 1024 * 1024 * 1024), '2.5 GB');
});

test('formatSize: drops the decimal once the number is big enough to not need it', () => {
  assert.strictEqual(formatSize(150 * 1024 * 1024), '150 MB');
});

test('formatSize: missing or nonsensical sizes render as a dash', () => {
  for (const v of [null, undefined, 0, -1, NaN, Infinity, '900']) {
    assert.strictEqual(formatSize(v), '—', 'failed for ' + String(v));
  }
});

// ------------------------------------------------------------- matchesQuery

const row = { name: 'Unofficial Skyrim Patch', modId: 'USSEP-266', version: '4.3.2', source: 'nexus' };

test('matchesQuery: an empty query matches everything', () => {
  for (const q of ['', '   ', null, undefined]) assert.strictEqual(matchesQuery(row, q), true);
});

test('matchesQuery: case-insensitive substring over name, id, version and source', () => {
  assert.strictEqual(matchesQuery(row, 'skyrim'), true);
  assert.strictEqual(matchesQuery(row, 'SKYRIM'), true);
  assert.strictEqual(matchesQuery(row, 'ussep'), true);
  assert.strictEqual(matchesQuery(row, '4.3'), true);
  assert.strictEqual(matchesQuery(row, 'nexus'), true);
  assert.strictEqual(matchesQuery(row, 'morrowind'), false);
});

test('matchesQuery: multiple terms all have to match, in any order', () => {
  assert.strictEqual(matchesQuery(row, 'unofficial patch'), true);
  assert.strictEqual(matchesQuery(row, 'patch unofficial'), true);
  assert.strictEqual(matchesQuery(row, 'unofficial morrowind'), false);
});

test('matchesQuery: surrounding whitespace is ignored', () => {
  assert.strictEqual(matchesQuery(row, '  skyrim  '), true);
});

test('matchesQuery: tolerates rows with missing fields', () => {
  assert.strictEqual(matchesQuery({ name: 'Solo' }, 'solo'), true);
  assert.strictEqual(matchesQuery({ name: 'Solo' }, 'nexus'), false);
});

// ------------------------------------------------- buildRows: size plumbing

test('buildRows: modSize is preferred over fileSize, and absence is null', () => {
  const rows = buildRows(vortex({
    both: { attributes: { name: 'Both', modSize: 100, fileSize: 999 } },
    only: { attributes: { name: 'Only', fileSize: 42 } },
    none: { attributes: { name: 'None' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.size]));
  assert.deepStrictEqual(by, { Both: 100, Only: 42, None: null });
});

// ------------------------------------------------- collection membership

// Collections reference their members by md5 / logicalFileName / description
// rather than by mod id, so membership is matched rather than looked up.
const coll = (rules) => ({
  type: 'collection',
  attributes: { customFileName: 'My Collection' },
  rules,
});
const requires = (ref) => ({ type: 'requires', reference: ref });
const recommends = (ref) => ({ type: 'recommends', reference: ref });

test('collectionMembership: matches a member by fileMD5', () => {
  const m = collectionMembership({
    c: coll([requires({ fileMD5: 'abc' })]),
    member: { attributes: { name: 'Member', fileMD5: 'abc' } },
  });
  assert.deepStrictEqual(m.get('member'), [{ collection: 'My Collection', optional: false }]);
});

test('collectionMembership: matches by logicalFileName', () => {
  const m = collectionMembership({
    c: coll([requires({ logicalFileName: 'Codeware' })]),
    member: { attributes: { name: 'Whatever', logicalFileName: 'Codeware' } },
  });
  assert.strictEqual(m.get('member')[0].collection, 'My Collection');
});

test('collectionMembership: matches by description against a mod name', () => {
  const m = collectionMembership({
    c: coll([requires({ description: 'SkyUI' })]),
    member: { attributes: { modName: 'SkyUI' } },
  });
  assert.strictEqual(m.get('member')[0].collection, 'My Collection');
});

test('collectionMembership: an md5 match wins over a name match', () => {
  // The precise key must be preferred, or a shared name could misattribute.
  const m = collectionMembership({
    c: coll([requires({ fileMD5: 'exact', description: 'Shared Name' })]),
    right: { attributes: { modName: 'Different', fileMD5: 'exact' } },
    wrong: { attributes: { modName: 'Shared Name' } },
  });
  assert.ok(m.has('right'), 'md5 match should win');
  assert.ok(!m.has('wrong'), 'name match should not also fire');
});

test('collectionMembership: recommends is marked optional, requires is not', () => {
  const m = collectionMembership({
    c: coll([requires({ fileMD5: 'a' }), recommends({ fileMD5: 'b' })]),
    req: { attributes: { fileMD5: 'a' } },
    rec: { attributes: { fileMD5: 'b' } },
  });
  assert.strictEqual(m.get('req')[0].optional, false);
  assert.strictEqual(m.get('rec')[0].optional, true);
});

test('collectionMembership: a rule matching nothing installed is skipped', () => {
  // Normal for a "recommends" the user declined -- not an error.
  const m = collectionMembership({ c: coll([requires({ fileMD5: 'missing' })]) });
  assert.strictEqual(m.size, 0);
});

test('collectionMembership: a collection is never a member of itself', () => {
  const m = collectionMembership({
    c: { type: 'collection', attributes: { customFileName: 'Self', fileMD5: 'x' },
         rules: [requires({ fileMD5: 'x' })] },
  });
  assert.strictEqual(m.size, 0);
});

test('collectionMembership: a mod in two collections reports both, once each', () => {
  const m = collectionMembership({
    c1: { type: 'collection', attributes: { customFileName: 'One' },
          rules: [requires({ fileMD5: 'a' }), requires({ fileMD5: 'a' })] },
    c2: { type: 'collection', attributes: { customFileName: 'Two' },
          rules: [requires({ fileMD5: 'a' })] },
    member: { attributes: { fileMD5: 'a' } },
  });
  assert.deepStrictEqual(m.get('member').map((e) => e.collection), ['One', 'Two']);
});

test('collectionMembership: no collections means no memberships', () => {
  assert.strictEqual(collectionMembership({ a: { attributes: { name: 'A' } } }).size, 0);
});

test('collectionLabel: formats one, many, optional, and none', () => {
  assert.strictEqual(collectionLabel([]), '');
  assert.strictEqual(collectionLabel(null), '');
  assert.strictEqual(collectionLabel([{ collection: 'A', optional: false }]), 'A');
  assert.strictEqual(collectionLabel([{ collection: 'A', optional: true }]), 'A (optional)');
  assert.strictEqual(
    collectionLabel([{ collection: 'A', optional: false }, { collection: 'B', optional: true }]),
    'A, B (optional)');
});

test('buildRows: attributes members and leaves non-members blank', () => {
  const rows = buildRows(vortex({
    c: { type: 'collection', attributes: { customFileName: 'Pack', source: 'nexus',
         collectionSlug: 'abc', downloadGame: 'skyrimse' },
         rules: [requires({ fileMD5: 'm1' })] },
    m1: { attributes: { name: 'In Pack', fileMD5: 'm1' } },
    m2: { attributes: { name: 'Standalone' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.collectionText]));
  assert.strictEqual(by['In Pack'], 'Pack');
  assert.strictEqual(by['Standalone'], '');
  assert.strictEqual(by['Pack'], '');
});

test('matchesQuery: searching a collection name finds its members', () => {
  assert.strictEqual(matchesQuery({ name: 'Codeware', collectionText: 'CET+Essentials' }, 'essentials'), true);
});

// ----------------------------------------------------------------- viewState

// The decision layer render() applies. Both render-layer bugs found during
// development were decision bugs, so this is where the safety net belongs.
const V = (modId, extra) => Object.assign(
  { modId, name: modId, version: '1.0', enabled: true, source: 'nexus' }, extra);

test('viewState: no options shows everything, sorted as given', () => {
  const v = viewState([V('A'), V('B')], {});
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['A', 'B']);
  assert.strictEqual(v.sort, 'name');
});

test('viewState: onlyEnabled drops disabled rows', () => {
  const v = viewState([V('On'), V('Off', { enabled: false })], { onlyEnabled: true });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['On']);
});

test('viewState: onlyEnabled is ignored when no row knows its status', () => {
  // Vortex's "all installed mods" view has no profile, so status is unknown.
  // Filtering there would empty the table for no reason.
  const v = viewState([V('A', { enabled: null }), V('B', { enabled: null })], { onlyEnabled: true });
  assert.strictEqual(v.rows.length, 2);
});

test('viewState: search filters, and sets the search-specific empty note', () => {
  const v = viewState([V('SkyUI'), V('Other')], { search: 'sky' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['SkyUI']);
  assert.match(v.emptyNote, /match that search/);
  assert.match(viewState([], {}).emptyNote, /current filter/);
});

// --- regression: the column-visibility bug ---
test('viewState: column flags reflect the data actually present', () => {
  const withAll = viewState([V('A', { size: 10, order: 1, collectionText: 'Pack' })], {});
  assert.deepStrictEqual(
    [withAll.hasSize, withAll.hasOrder, withAll.hasColl], [true, true, true]);
  const withNone = viewState([V('A')], {});
  assert.deepStrictEqual(
    [withNone.hasSize, withNone.hasOrder, withNone.hasColl], [false, false, false]);
});

test('viewState: searching down to a row without a size keeps the size column', () => {
  // Regression: column flags must come from the unfiltered set. Deciding from
  // the filtered rows made the column vanish mid-search.
  const rows = [V('Big', { size: 1000 }), V('Sizeless')];
  const v = viewState(rows, { search: 'sizeless' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['Sizeless']);
  assert.strictEqual(v.hasSize, true, 'size column should survive the search');
});

test('viewState: flags are computed after the enabled filter, not before', () => {
  // A disabled row is the only one with an order; hiding it should hide the column.
  const v = viewState([V('On'), V('Off', { enabled: false, order: 1 })], { onlyEnabled: true });
  assert.strictEqual(v.hasOrder, false);
});

// --- sorting ---
test('viewState: sorts by size, largest first, with missing sizes last', () => {
  const v = viewState([V('S', { size: 5 }), V('L', { size: 500 }), V('None')], { sort: 'size' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['L', 'S', 'None']);
});

test('viewState: sorts by order when order exists', () => {
  const v = viewState([V('Second', { order: 2 }), V('First', { order: 1 })], { sort: 'order' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['First', 'Second']);
});

test('viewState: falls back to name when order is asked for but absent', () => {
  // Regression-guard: the control must not be left pointing at a dead sort.
  const v = viewState([V('A'), V('B')], { sort: 'order' });
  assert.strictEqual(v.sort, 'name');
  assert.strictEqual(v.rows.length, 2);
});

// --- totals ---
test('viewState: totals only the rows actually shown', () => {
  const rows = [V('A', { size: 100 }), V('B', { size: 900 })];
  assert.strictEqual(viewState(rows, {}).totalBytes, 1000);
  assert.strictEqual(viewState(rows, { search: 'A' }).totalBytes, 100);
  assert.strictEqual(viewState(rows, { onlyEnabled: true }).totalBytes, 1000);
});

test('viewState: no sizes means no size text at all', () => {
  assert.strictEqual(viewState([V('A')], {}).sizeTotalText, '');
  assert.match(viewState([V('A', { size: 1024 })], {}).sizeTotalText, /1.0 KB on disk/);
});

test('viewState: does not mutate the array it is given', () => {
  const rows = [V('B', { size: 1 }), V('A', { size: 2 })];
  const before = rows.map((r) => r.modId);
  viewState(rows, { sort: 'size' });
  assert.deepStrictEqual(rows.map((r) => r.modId), before);
});

test('viewState: tolerates an empty or missing row set', () => {
  for (const input of [[], null, undefined]) {
    const v = viewState(input, {});
    assert.deepStrictEqual(v.rows, []);
    assert.strictEqual(v.totalBytes, 0);
  }
});

// ------------------------------------------------ missing collection members

test('missingCollectionMembers: reports a rule nothing installed satisfies', () => {
  const m = missingCollectionMembers({
    c: coll([requires({ description: 'Absent Mod' })]),
  });
  assert.deepStrictEqual(m, [{ name: 'Absent Mod', collection: 'My Collection', optional: false }]);
});

test('missingCollectionMembers: says nothing about members that ARE installed', () => {
  const m = missingCollectionMembers({
    c: coll([requires({ fileMD5: 'here' })]),
    installed: { attributes: { name: 'Here', fileMD5: 'here' } },
  });
  assert.deepStrictEqual(m, []);
});

test('missingCollectionMembers: marks recommendations as optional', () => {
  const m = missingCollectionMembers({ c: coll([recommends({ description: 'Nice To Have' })]) });
  assert.strictEqual(m[0].optional, true);
});

test('missingCollectionMembers: falls back to logicalFileName for a name', () => {
  const m = missingCollectionMembers({ c: coll([requires({ logicalFileName: 'SomePlugin' })]) });
  assert.strictEqual(m[0].name, 'SomePlugin');
});

test('missingCollectionMembers: a rule with no usable name is skipped', () => {
  // Nothing useful could be shown for it, so reporting it would just confuse.
  assert.deepStrictEqual(missingCollectionMembers({ c: coll([requires({ fileMD5: 'x' })]) }), []);
});

test('missingCollectionMembers: the same absent mod is not listed twice per collection', () => {
  const m = missingCollectionMembers({
    c: coll([requires({ description: 'Absent' }), requires({ description: 'Absent' })]),
  });
  assert.strictEqual(m.length, 1);
});

test('missingCollectionMembers: no collections means nothing missing', () => {
  assert.deepStrictEqual(missingCollectionMembers({ a: { attributes: { name: 'A' } } }), []);
});

// ------------------------------------------------------------- endorsement

test('endorsementLabel: maps every state Vortex records', () => {
  assert.strictEqual(endorsementLabel('Endorsed'), 'yes');
  assert.strictEqual(endorsementLabel('Undecided'), 'not yet');
  assert.strictEqual(endorsementLabel('pending'), 'not yet');
  assert.strictEqual(endorsementLabel('Abstained'), 'abstained');
  assert.strictEqual(endorsementLabel(undefined), '—');
  assert.strictEqual(endorsementLabel(null), '—');
});

test('isUnendorsed: only genuinely undecided counts', () => {
  // Abstained is a decision, and an absent value means the mod can't be
  // endorsed at all -- neither belongs on a "you should endorse these" list.
  assert.strictEqual(isUnendorsed('Undecided'), true);
  assert.strictEqual(isUnendorsed('pending'), true);
  assert.strictEqual(isUnendorsed('Endorsed'), false);
  assert.strictEqual(isUnendorsed('Abstained'), false);
  assert.strictEqual(isUnendorsed(undefined), false);
});

test('buildRows: carries the endorsement state through', () => {
  const rows = buildRows(vortex({
    a: { attributes: { name: 'A', endorsed: 'Endorsed' } },
    b: { attributes: { name: 'B' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.endorsed]));
  assert.strictEqual(by.A, 'Endorsed');
  assert.strictEqual(by.B, undefined);
});

test('viewState: the not-endorsed filter keeps only undecided mods', () => {
  const rows = [
    V('Done', { endorsed: 'Endorsed' }),
    V('Todo', { endorsed: 'Undecided' }),
    V('No', { endorsed: 'Abstained' }),
    V('NA'),
  ];
  const v = viewState(rows, { notEndorsedOnly: true });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['Todo']);
});

test('viewState: hasEndo reflects whether any endorsement data exists', () => {
  assert.strictEqual(viewState([V('A', { endorsed: 'Undecided' })], {}).hasEndo, true);
  assert.strictEqual(viewState([V('A')], {}).hasEndo, false);
});

// -------------------------------------------------- optional: real backups

const backupDir = process.env.APPDATA
  ? path.join(process.env.APPDATA, 'Vortex', 'temp', 'state_backups_full')
  : null;
const realBackups = backupDir && fs.existsSync(backupDir)
  ? fs.readdirSync(backupDir).filter((f) => f.endsWith('.json')).map((f) => path.join(backupDir, f))
  : [];

test('real Vortex backups on this machine parse and diff', {
  skip: realBackups.length < 2 ? 'needs two local Vortex state backups; none committed to the repo' : false,
}, () => {
  const sources = realBackups.slice(0, 2).map((f) => {
    const res = parseModlist(fs.readFileSync(f, 'utf8'));
    assert.ok(!res.error, 'failed to parse ' + path.basename(f) + ': ' + res.error);
    assert.strictEqual(res.source.type, 'vortex');
    return res.source;
  });

  const games = Object.keys(sources[0].mods);
  assert.ok(games.length > 0, 'expected at least one game in a real backup');

  for (const game of games) {
    const a = buildRows(sources[0], game, '__all__');
    const b = buildRows(sources[1], game, '__all__');
    for (const row of a.concat(b)) {
      assert.ok(typeof row.name === 'string' && row.name.length > 0, 'every row needs a name');
      if (row.sourceUrl) {
        assert.match(row.sourceUrl, /^https:\/\/www\.nexusmods\.com\//, 'links must point at nexusmods.com');
      }
    }
    // Must not throw, and must account for every mod on both sides.
    const d = diffRows(a, b);
    const ids = new Set(a.concat(b).map((r) => r.modId));
    assert.strictEqual(d.length, ids.size);
  }
});
