'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const { parseMO2, parseModlist, diffRows, buildRows, csvCell, formatSize, matchesQuery,
        collectionMembership, collectionLabel, viewState,
        missingCollectionMembers, endorsementLabel, isUnendorsed,
        defaultProfileFor, gamesWithMods, allGamesRows,
        installedAt, installedLabel, nexusPageCounts,
        loadOrderFor, gamesWithLoadOrder, loadOrderNote, allGamesFileName,
        columnsIn, csvStatus, statusLabel,
        mdCell, bbSafe, safeHttpUrl, mdLink, bbLink,
        markdownLines, bbcodeLines, markdownDiffLines, bbcodeDiffLines,
        themeIds, resolveTheme, themeMeta, legacyThemeId } = require('./extract.js');

const NL = '\n';
const mo2 = (...lines) => lines.join(NL);

// ---------------------------------------------------------------- parseMO2

test('parseMO2: markers set enabled state', () => {
  const e = parseMO2(mo2('+On', '-Off', '*Unmanaged'));
  assert.deepStrictEqual(e.map((x) => [x.name, x.enabled, x.unmanaged]), [
    ['On', true, false],
    ['Off', false, false],
    ['Unmanaged', true, true],
  ]);
});

test('parseMO2: comments, blanks and unmarked lines are skipped', () => {
  const e = parseMO2(mo2('# generated by Mod Organizer', '', '   ', 'no marker here', '+Real'));
  assert.deepStrictEqual(e.map((x) => x.name), ['Real']);
});

test('parseMO2: names are trimmed', () => {
  assert.strictEqual(parseMO2('+   Spaced Name   ')[0].name, 'Spaced Name');
});

test('parseMO2: CRLF files parse identically to LF', () => {
  const lines = ['# gen', '+A', '-B'];
  assert.deepStrictEqual(parseMO2(lines.join('\r\n')), parseMO2(lines.join('\n')));
});

test('parseMO2: separators are excluded but still consume a file position', () => {
  // Separators occupy a slot in MO2's pane, so dropping their position would
  // shift every mod below them.
  const e = parseMO2(mo2('+First', '+Section_separator', '+Second'));
  assert.deepStrictEqual(e.map((x) => x.name), ['First', 'Second']);
  assert.deepStrictEqual(e.map((x) => x.filePosition), [0, 2]);
});

test('parseMO2: empty input yields no entries', () => {
  assert.deepStrictEqual(parseMO2(''), []);
});

// ------------------------------------------------------------ parseModlist

test('parseModlist: detects a Vortex state file', () => {
  const res = parseModlist(JSON.stringify({ persistent: { mods: { skyrimse: { a: {} } }, profiles: {} } }));
  assert.strictEqual(res.source.type, 'vortex');
});

test('parseModlist: accepts an unwrapped Vortex backup', () => {
  // Some backups are stored without the `persistent` wrapper.
  const res = parseModlist(JSON.stringify({ mods: { skyrimse: { a: {} } }, profiles: {} }));
  assert.strictEqual(res.source.type, 'vortex');
});

test('parseModlist: detects an MO2 modlist', () => {
  assert.strictEqual(parseModlist(mo2('# gen', '+A')).source.type, 'mo2');
});

test('parseModlist: JSON with no mods is rejected with the keys it did contain', () => {
  const res = parseModlist(JSON.stringify({ settings: 1, window: 2 }));
  assert.ok(res.error);
  assert.match(res.error, /settings, window/);
});

test('parseModlist: truncated JSON is reported as truncated, not as the wrong file', () => {
  const res = parseModlist('{"persistent":{"mods":{"skyrimse":{"a":{"attribu');
  assert.ok(res.error);
  assert.match(res.error, /truncated|mid-save/);
});

test('parseModlist: unrecognised text is rejected', () => {
  const res = parseModlist('just some notes' + NL + 'nothing structured');
  assert.ok(res.error);
  assert.match(res.error, /Couldn't recognize/);
});

// ------------------------------------------------------- buildRows: Vortex

const vortex = (mods, profiles) => ({ type: 'vortex', mods: { skyrimse: mods }, profiles: profiles || {} });

test('buildRows: name falls back through the attribute chain', () => {
  const rows = buildRows(vortex({
    a: { attributes: { customFileName: 'Custom', name: 'Name' } },
    b: { attributes: { name: 'Name' } },
    c: { attributes: { logicalFileName: 'Logical' } },
    d: { attributes: {} },
  }), 'skyrimse', '__all__');
  const byId = Object.fromEntries(rows.map((r) => [r.modId, r.name]));
  assert.deepStrictEqual(byId, { a: 'Custom', b: 'Name', c: 'Logical', d: 'd' });
});

test('buildRows: a Nexus mod links to its mod page', () => {
  const [row] = buildRows(vortex({ a: { attributes: { name: 'A', source: 'nexus', modId: 6276 } } }), 'skyrimse', '__all__');
  assert.strictEqual(row.sourceUrl, 'https://www.nexusmods.com/skyrimse/mods/6276');
});

test('buildRows: a non-numeric modId does not produce a link', () => {
  const [row] = buildRows(vortex({ a: { attributes: { name: 'A', source: 'nexus', modId: '1 onmouseover=alert(1)' } } }), 'skyrimse', '__all__');
  assert.strictEqual(row.sourceUrl, null);
});

test('buildRows: a collection links to the collection page and is labelled', () => {
  const [row] = buildRows(vortex({
    c: { type: 'collection', attributes: { name: 'Coll', source: 'nexus', collectionSlug: 'n0nymh', downloadGame: 'cyberpunk2077' } },
  }), 'skyrimse', '__all__');
  assert.strictEqual(row.source, 'collection');
  assert.strictEqual(row.sourceUrl, 'https://www.nexusmods.com/games/cyberpunk2077/collections/n0nymh');
});

test('buildRows: a collection slug containing path traversal is not linked', () => {
  const [row] = buildRows(vortex({
    c: { type: 'collection', attributes: { name: 'Sketchy', collectionSlug: 'evil/../../x', downloadGame: 'cyberpunk2077' } },
  }), 'skyrimse', '__all__');
  assert.strictEqual(row.source, 'collection');
  assert.strictEqual(row.sourceUrl, null);
});

test('buildRows: enabled is null without a profile and boolean with one', () => {
  const mods = { a: { attributes: { name: 'A' } } };
  const profiles = { p1: { gameId: 'skyrimse', name: 'Main', modState: { a: { enabled: false } } } };
  assert.strictEqual(buildRows(vortex(mods, profiles), 'skyrimse', '__all__')[0].enabled, null);
  assert.strictEqual(buildRows(vortex(mods, profiles), 'skyrimse', 'p1')[0].enabled, false);
});

test('buildRows: an unknown game yields no rows rather than throwing', () => {
  assert.deepStrictEqual(buildRows(vortex({ a: { attributes: {} } }), 'nosuchgame', '__all__'), []);
});

// ---------------------------------------------------------- buildRows: MO2

test('buildRows: MO2 order is the reverse of file order', () => {
  // VERIFIED against a real profile: modlist.txt is written bottom-to-top
  // relative to MO2's pane, so the last line is the top of the pane.
  const source = { type: 'mo2', entries: parseMO2(mo2('+Bottom', '+Middle', '+Top')) };
  const rows = buildRows(source, null, null);
  const rank = Object.fromEntries(rows.map((r) => [r.name, r.order]));
  assert.deepStrictEqual(rank, { Top: 1, Middle: 2, Bottom: 3 });
});

test('buildRows: a separator consumes a rank without appearing', () => {
  const source = { type: 'mo2', entries: parseMO2(mo2('+Bottom', '+Sep_separator', '+Top')) };
  const rows = buildRows(source, null, null);
  assert.deepStrictEqual(rows.map((r) => r.name).sort(), ['Bottom', 'Top']);
  assert.deepStrictEqual(Object.fromEntries(rows.map((r) => [r.name, r.order])), { Top: 1, Bottom: 2 });
});

// ----------------------------------------------------------------- diffRows

const R = (modId, extra) => Object.assign({ modId, name: modId, version: '1.0', enabled: true }, extra);

test('diffRows: classifies added, removed, changed and unchanged', () => {
  const d = diffRows(
    [R('Same'), R('Bumped'), R('Dropped')],
    [R('Same'), R('Bumped', { version: '2.0' }), R('Fresh')]
  );
  const by = Object.fromEntries(d.map((x) => [x.row.modId, x.change]));
  assert.deepStrictEqual(by, { Same: 'unchanged', Bumped: 'changed', Dropped: 'removed', Fresh: 'added' });
});

test('diffRows: records from/to for version, status and order', () => {
  const [d] = diffRows(
    [R('M', { version: '1.0', enabled: true, order: 5 })],
    [R('M', { version: '2.0', enabled: false, order: 1 })]
  );
  assert.deepStrictEqual(
    d.changes.map((c) => [c.field, String(c.from), String(c.to)]).sort(),
    [['order', '5', '1'], ['status', 'enabled', 'disabled'], ['version', '1.0', '2.0']].sort()
  );
});

test('diffRows: an unknown status on either side is not a change', () => {
  // Vortex keeps enabled state on the profile. When the selected profile is
  // absent from the other file that side falls back to its full installed
  // list, where status is unknown. Treating unknown as a change marked every
  // single mod as modified.
  assert.strictEqual(diffRows([R('M', { enabled: true })], [R('M', { enabled: null })])[0].change, 'unchanged');
  assert.strictEqual(diffRows([R('M', { enabled: null })], [R('M', { enabled: true })])[0].change, 'unchanged');
});

test('diffRows: a real status flip is still reported', () => {
  const [d] = diffRows([R('M', { enabled: true })], [R('M', { enabled: false })]);
  assert.strictEqual(d.changes[0].field, 'status');
});

test('diffRows: a removed entry carries the old row', () => {
  const [d] = diffRows([R('Gone', { version: '9.9' })], []);
  assert.strictEqual(d.change, 'removed');
  assert.strictEqual(d.row.version, '9.9');
});

test('diffRows: groups added, removed, changed, unchanged in that order', () => {
  const d = diffRows([R('Keep'), R('Old')], [R('Keep'), R('New')]);
  const rank = { added: 0, removed: 1, changed: 2, unchanged: 3 };
  const seen = d.map((x) => rank[x.change]);
  assert.deepStrictEqual(seen, [...seen].sort((a, b) => a - b));
});

test('diffRows: empty inputs', () => {
  assert.deepStrictEqual(diffRows([], []), []);
  assert.strictEqual(diffRows([], [R('A')])[0].change, 'added');
  assert.strictEqual(diffRows([R('A')], [])[0].change, 'removed');
});

// ------------------------------------------------------------------ csvCell

test('csvCell: quotes are doubled', () => {
  assert.strictEqual(csvCell('say "hi"'), '"say ""hi"""');
});

test('csvCell: formula-leading characters are neutralised', () => {
  // Mod names are written by mod authors and end up in a spreadsheet.
  for (const lead of ['=', '+', '-', '@']) {
    assert.strictEqual(csvCell(lead + 'cmd|calc'), '"\'' + lead + 'cmd|calc"');
  }
});

test('csvCell: ordinary values are untouched', () => {
  assert.strictEqual(csvCell('Normal Mod'), '"Normal Mod"');
});

// --------------------------------------------------------------- formatSize

test('formatSize: scales through units', () => {
  assert.strictEqual(formatSize(512), '512 B');
  assert.strictEqual(formatSize(1024), '1.0 KB');
  assert.strictEqual(formatSize(5 * 1024 * 1024), '5.0 MB');
  assert.strictEqual(formatSize(2.5 * 1024 * 1024 * 1024), '2.5 GB');
});

test('formatSize: drops the decimal once the number is big enough to not need it', () => {
  assert.strictEqual(formatSize(150 * 1024 * 1024), '150 MB');
});

test('formatSize: missing or nonsensical sizes render as a dash', () => {
  for (const v of [null, undefined, 0, -1, NaN, Infinity, '900']) {
    assert.strictEqual(formatSize(v), '—', 'failed for ' + String(v));
  }
});

// ------------------------------------------------------------- matchesQuery

const row = { name: 'Unofficial Skyrim Patch', modId: 'USSEP-266', version: '4.3.2', source: 'nexus' };

test('matchesQuery: an empty query matches everything', () => {
  for (const q of ['', '   ', null, undefined]) assert.strictEqual(matchesQuery(row, q), true);
});

test('matchesQuery: case-insensitive substring over name, id, version and source', () => {
  assert.strictEqual(matchesQuery(row, 'skyrim'), true);
  assert.strictEqual(matchesQuery(row, 'SKYRIM'), true);
  assert.strictEqual(matchesQuery(row, 'ussep'), true);
  assert.strictEqual(matchesQuery(row, '4.3'), true);
  assert.strictEqual(matchesQuery(row, 'nexus'), true);
  assert.strictEqual(matchesQuery(row, 'morrowind'), false);
});

test('matchesQuery: multiple terms all have to match, in any order', () => {
  assert.strictEqual(matchesQuery(row, 'unofficial patch'), true);
  assert.strictEqual(matchesQuery(row, 'patch unofficial'), true);
  assert.strictEqual(matchesQuery(row, 'unofficial morrowind'), false);
});

test('matchesQuery: surrounding whitespace is ignored', () => {
  assert.strictEqual(matchesQuery(row, '  skyrim  '), true);
});

test('matchesQuery: tolerates rows with missing fields', () => {
  assert.strictEqual(matchesQuery({ name: 'Solo' }, 'solo'), true);
  assert.strictEqual(matchesQuery({ name: 'Solo' }, 'nexus'), false);
});

// ------------------------------------------------- buildRows: size plumbing

test('buildRows: modSize is preferred over fileSize, and absence is null', () => {
  const rows = buildRows(vortex({
    both: { attributes: { name: 'Both', modSize: 100, fileSize: 999 } },
    only: { attributes: { name: 'Only', fileSize: 42 } },
    none: { attributes: { name: 'None' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.size]));
  assert.deepStrictEqual(by, { Both: 100, Only: 42, None: null });
});

// ------------------------------------------------- collection membership

// Collections reference their members by md5 / logicalFileName / description
// rather than by mod id, so membership is matched rather than looked up.
const coll = (rules) => ({
  type: 'collection',
  attributes: { customFileName: 'My Collection' },
  rules,
});
const requires = (ref) => ({ type: 'requires', reference: ref });
const recommends = (ref) => ({ type: 'recommends', reference: ref });

test('collectionMembership: matches a member by fileMD5', () => {
  const m = collectionMembership({
    c: coll([requires({ fileMD5: 'abc' })]),
    member: { attributes: { name: 'Member', fileMD5: 'abc' } },
  });
  assert.deepStrictEqual(m.get('member'), [{ collection: 'My Collection', optional: false }]);
});

test('collectionMembership: matches by logicalFileName', () => {
  const m = collectionMembership({
    c: coll([requires({ logicalFileName: 'Codeware' })]),
    member: { attributes: { name: 'Whatever', logicalFileName: 'Codeware' } },
  });
  assert.strictEqual(m.get('member')[0].collection, 'My Collection');
});

test('collectionMembership: matches by description against a mod name', () => {
  const m = collectionMembership({
    c: coll([requires({ description: 'SkyUI' })]),
    member: { attributes: { modName: 'SkyUI' } },
  });
  assert.strictEqual(m.get('member')[0].collection, 'My Collection');
});

test('collectionMembership: an md5 match wins over a name match', () => {
  // The precise key must be preferred, or a shared name could misattribute.
  const m = collectionMembership({
    c: coll([requires({ fileMD5: 'exact', description: 'Shared Name' })]),
    right: { attributes: { modName: 'Different', fileMD5: 'exact' } },
    wrong: { attributes: { modName: 'Shared Name' } },
  });
  assert.ok(m.has('right'), 'md5 match should win');
  assert.ok(!m.has('wrong'), 'name match should not also fire');
});

test('collectionMembership: recommends is marked optional, requires is not', () => {
  const m = collectionMembership({
    c: coll([requires({ fileMD5: 'a' }), recommends({ fileMD5: 'b' })]),
    req: { attributes: { fileMD5: 'a' } },
    rec: { attributes: { fileMD5: 'b' } },
  });
  assert.strictEqual(m.get('req')[0].optional, false);
  assert.strictEqual(m.get('rec')[0].optional, true);
});

test('collectionMembership: a rule matching nothing installed is skipped', () => {
  // Normal for a "recommends" the user declined -- not an error.
  const m = collectionMembership({ c: coll([requires({ fileMD5: 'missing' })]) });
  assert.strictEqual(m.size, 0);
});

test('collectionMembership: a collection is never a member of itself', () => {
  const m = collectionMembership({
    c: { type: 'collection', attributes: { customFileName: 'Self', fileMD5: 'x' },
         rules: [requires({ fileMD5: 'x' })] },
  });
  assert.strictEqual(m.size, 0);
});

test('collectionMembership: a mod in two collections reports both, once each', () => {
  const m = collectionMembership({
    c1: { type: 'collection', attributes: { customFileName: 'One' },
          rules: [requires({ fileMD5: 'a' }), requires({ fileMD5: 'a' })] },
    c2: { type: 'collection', attributes: { customFileName: 'Two' },
          rules: [requires({ fileMD5: 'a' })] },
    member: { attributes: { fileMD5: 'a' } },
  });
  assert.deepStrictEqual(m.get('member').map((e) => e.collection), ['One', 'Two']);
});

test('collectionMembership: no collections means no memberships', () => {
  assert.strictEqual(collectionMembership({ a: { attributes: { name: 'A' } } }).size, 0);
});

test('collectionLabel: formats one, many, optional, and none', () => {
  assert.strictEqual(collectionLabel([]), '');
  assert.strictEqual(collectionLabel(null), '');
  assert.strictEqual(collectionLabel([{ collection: 'A', optional: false }]), 'A');
  assert.strictEqual(collectionLabel([{ collection: 'A', optional: true }]), 'A (optional)');
  assert.strictEqual(
    collectionLabel([{ collection: 'A', optional: false }, { collection: 'B', optional: true }]),
    'A, B (optional)');
});

test('buildRows: attributes members and leaves non-members blank', () => {
  const rows = buildRows(vortex({
    c: { type: 'collection', attributes: { customFileName: 'Pack', source: 'nexus',
         collectionSlug: 'abc', downloadGame: 'skyrimse' },
         rules: [requires({ fileMD5: 'm1' })] },
    m1: { attributes: { name: 'In Pack', fileMD5: 'm1' } },
    m2: { attributes: { name: 'Standalone' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.collectionText]));
  assert.strictEqual(by['In Pack'], 'Pack');
  assert.strictEqual(by['Standalone'], '');
  assert.strictEqual(by['Pack'], '');
});

test('matchesQuery: searching a collection name finds its members', () => {
  assert.strictEqual(matchesQuery({ name: 'Codeware', collectionText: 'CET+Essentials' }, 'essentials'), true);
});

// ----------------------------------------------------------------- viewState

// The decision layer render() applies. Both render-layer bugs found during
// development were decision bugs, so this is where the safety net belongs.
const V = (modId, extra) => Object.assign(
  { modId, name: modId, version: '1.0', enabled: true, source: 'nexus' }, extra);

test('viewState: no options shows everything, sorted as given', () => {
  const v = viewState([V('A'), V('B')], {});
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['A', 'B']);
  assert.strictEqual(v.sort, 'name');
});

test('viewState: onlyEnabled drops disabled rows', () => {
  const v = viewState([V('On'), V('Off', { enabled: false })], { onlyEnabled: true });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['On']);
});

test('viewState: onlyEnabled is ignored when no row knows its status', () => {
  // Vortex's "all installed mods" view has no profile, so status is unknown.
  // Filtering there would empty the table for no reason.
  const v = viewState([V('A', { enabled: null }), V('B', { enabled: null })], { onlyEnabled: true });
  assert.strictEqual(v.rows.length, 2);
});

test('viewState: search filters, and sets the search-specific empty note', () => {
  const v = viewState([V('SkyUI'), V('Other')], { search: 'sky' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['SkyUI']);
  assert.match(v.emptyNote, /match that search/);
  assert.match(viewState([], {}).emptyNote, /current filter/);
});

// --- regression: the column-visibility bug ---
test('viewState: column flags reflect the data actually present', () => {
  const withAll = viewState([V('A', { size: 10, order: 1, collectionText: 'Pack' })], {});
  assert.deepStrictEqual(
    [withAll.hasSize, withAll.hasOrder, withAll.hasColl], [true, true, true]);
  const withNone = viewState([V('A')], {});
  assert.deepStrictEqual(
    [withNone.hasSize, withNone.hasOrder, withNone.hasColl], [false, false, false]);
});

test('viewState: searching down to a row without a size keeps the size column', () => {
  // Regression: column flags must come from the unfiltered set. Deciding from
  // the filtered rows made the column vanish mid-search.
  const rows = [V('Big', { size: 1000 }), V('Sizeless')];
  const v = viewState(rows, { search: 'sizeless' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['Sizeless']);
  assert.strictEqual(v.hasSize, true, 'size column should survive the search');
});

test('viewState: flags are computed after the enabled filter, not before', () => {
  // A disabled row is the only one with an order; hiding it should hide the column.
  const v = viewState([V('On'), V('Off', { enabled: false, order: 1 })], { onlyEnabled: true });
  assert.strictEqual(v.hasOrder, false);
});

// --- sorting ---
test('viewState: sorts by size, largest first, with missing sizes last', () => {
  const v = viewState([V('S', { size: 5 }), V('L', { size: 500 }), V('None')], { sort: 'size' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['L', 'S', 'None']);
});

test('viewState: sorts by order when order exists', () => {
  const v = viewState([V('Second', { order: 2 }), V('First', { order: 1 })], { sort: 'order' });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['First', 'Second']);
});

test('viewState: falls back to name when order is asked for but absent', () => {
  // Regression-guard: the control must not be left pointing at a dead sort.
  const v = viewState([V('A'), V('B')], { sort: 'order' });
  assert.strictEqual(v.sort, 'name');
  assert.strictEqual(v.rows.length, 2);
});

// --- totals ---
test('viewState: totals only the rows actually shown', () => {
  const rows = [V('A', { size: 100 }), V('B', { size: 900 })];
  assert.strictEqual(viewState(rows, {}).totalBytes, 1000);
  assert.strictEqual(viewState(rows, { search: 'A' }).totalBytes, 100);
  assert.strictEqual(viewState(rows, { onlyEnabled: true }).totalBytes, 1000);
});

test('viewState: no sizes means no size text at all', () => {
  assert.strictEqual(viewState([V('A')], {}).sizeTotalText, '');
  assert.match(viewState([V('A', { size: 1024 })], {}).sizeTotalText, /1.0 KB on disk/);
});

test('viewState: does not mutate the array it is given', () => {
  const rows = [V('B', { size: 1 }), V('A', { size: 2 })];
  const before = rows.map((r) => r.modId);
  viewState(rows, { sort: 'size' });
  assert.deepStrictEqual(rows.map((r) => r.modId), before);
});

test('viewState: tolerates an empty or missing row set', () => {
  for (const input of [[], null, undefined]) {
    const v = viewState(input, {});
    assert.deepStrictEqual(v.rows, []);
    assert.strictEqual(v.totalBytes, 0);
  }
});

// ------------------------------------------------ missing collection members

test('missingCollectionMembers: reports a rule nothing installed satisfies', () => {
  const m = missingCollectionMembers({
    c: coll([requires({ description: 'Absent Mod' })]),
  });
  assert.deepStrictEqual(m, [{ name: 'Absent Mod', collection: 'My Collection', optional: false }]);
});

test('missingCollectionMembers: says nothing about members that ARE installed', () => {
  const m = missingCollectionMembers({
    c: coll([requires({ fileMD5: 'here' })]),
    installed: { attributes: { name: 'Here', fileMD5: 'here' } },
  });
  assert.deepStrictEqual(m, []);
});

test('missingCollectionMembers: marks recommendations as optional', () => {
  const m = missingCollectionMembers({ c: coll([recommends({ description: 'Nice To Have' })]) });
  assert.strictEqual(m[0].optional, true);
});

test('missingCollectionMembers: falls back to logicalFileName for a name', () => {
  const m = missingCollectionMembers({ c: coll([requires({ logicalFileName: 'SomePlugin' })]) });
  assert.strictEqual(m[0].name, 'SomePlugin');
});

test('missingCollectionMembers: a rule with no usable name is skipped', () => {
  // Nothing useful could be shown for it, so reporting it would just confuse.
  assert.deepStrictEqual(missingCollectionMembers({ c: coll([requires({ fileMD5: 'x' })]) }), []);
});

test('missingCollectionMembers: the same absent mod is not listed twice per collection', () => {
  const m = missingCollectionMembers({
    c: coll([requires({ description: 'Absent' }), requires({ description: 'Absent' })]),
  });
  assert.strictEqual(m.length, 1);
});

test('missingCollectionMembers: no collections means nothing missing', () => {
  assert.deepStrictEqual(missingCollectionMembers({ a: { attributes: { name: 'A' } } }), []);
});

// ------------------------------------------------------------- endorsement

test('endorsementLabel: maps every state Vortex records', () => {
  assert.strictEqual(endorsementLabel('Endorsed'), 'yes');
  assert.strictEqual(endorsementLabel('Undecided'), 'not yet');
  assert.strictEqual(endorsementLabel('pending'), 'not yet');
  assert.strictEqual(endorsementLabel('Abstained'), 'abstained');
  assert.strictEqual(endorsementLabel(undefined), '—');
  assert.strictEqual(endorsementLabel(null), '—');
});

test('isUnendorsed: only genuinely undecided counts', () => {
  // Abstained is a decision, and an absent value means the mod can't be
  // endorsed at all -- neither belongs on a "you should endorse these" list.
  assert.strictEqual(isUnendorsed('Undecided'), true);
  assert.strictEqual(isUnendorsed('pending'), true);
  assert.strictEqual(isUnendorsed('Endorsed'), false);
  assert.strictEqual(isUnendorsed('Abstained'), false);
  assert.strictEqual(isUnendorsed(undefined), false);
});

test('buildRows: carries the endorsement state through', () => {
  const rows = buildRows(vortex({
    a: { attributes: { name: 'A', endorsed: 'Endorsed' } },
    b: { attributes: { name: 'B' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r.endorsed]));
  assert.strictEqual(by.A, 'Endorsed');
  assert.strictEqual(by.B, undefined);
});

test('viewState: the not-endorsed filter keeps only undecided mods', () => {
  const rows = [
    V('Done', { endorsed: 'Endorsed' }),
    V('Todo', { endorsed: 'Undecided' }),
    V('No', { endorsed: 'Abstained' }),
    V('NA'),
  ];
  const v = viewState(rows, { notEndorsedOnly: true });
  assert.deepStrictEqual(v.rows.map((r) => r.modId), ['Todo']);
});

test('viewState: hasEndo reflects whether any endorsement data exists', () => {
  assert.strictEqual(viewState([V('A', { endorsed: 'Undecided' })], {}).hasEndo, true);
  assert.strictEqual(viewState([V('A')], {}).hasEndo, false);
});

// --------------------------------------------------------------- load order

// A plugin is a file inside a mod; one mod can ship several or none. The load
// order is therefore its own list, not a column on the mod list, and these
// entries stand alone -- Vortex records a name and enabled flag for each.
const withOrder = (loadOrder, profiles) => ({
  type: 'vortex',
  mods: { morrowind: { a: { attributes: { name: 'A' } } } },
  profiles: profiles || { pm: { gameId: 'morrowind', name: 'Default', lastActivated: 9 } },
  loadOrder,
});

test('loadOrderFor: numbers plugins from 1 in file order', () => {
  const lo = loadOrderFor(withOrder({ pm: [
    { name: 'Morrowind.esm', enabled: true },
    { name: 'Tribunal.esm', enabled: false },
  ] }), 'morrowind', '__all__');
  assert.deepStrictEqual(lo, [
    { position: 1, name: 'Morrowind.esm', enabled: true },
    { position: 2, name: 'Tribunal.esm', enabled: false },
  ]);
});

test('loadOrderFor: falls back to id when an entry has no name', () => {
  const lo = loadOrderFor(withOrder({ pm: [{ id: 'Thing.esp', enabled: true }] }), 'morrowind', '__all__');
  assert.strictEqual(lo[0].name, 'Thing.esp');
});

test('loadOrderFor: entries with neither name nor id are dropped', () => {
  const lo = loadOrderFor(withOrder({ pm: [{ enabled: true }, { name: 'Real.esp' }] }), 'morrowind', '__all__');
  assert.deepStrictEqual(lo.map((e) => e.name), ['Real.esp']);
  assert.strictEqual(lo[0].position, 1, 'numbering restarts after a dropped entry');
});

test('loadOrderFor: a missing enabled flag reads as disabled, not as unknown', () => {
  // Unlike a mod's status, a plugin is either in the order or it is not.
  assert.strictEqual(loadOrderFor(withOrder({ pm: [{ name: 'X.esp' }] }), 'morrowind', '__all__')[0].enabled, false);
});

test('loadOrderFor: uses the named profile when it has an order', () => {
  const src = withOrder(
    { pm: [{ name: 'FromDefault.esp' }], other: [{ name: 'FromOther.esp' }] },
    { pm: { gameId: 'morrowind', lastActivated: 9 }, other: { gameId: 'morrowind', lastActivated: 1 } });
  assert.strictEqual(loadOrderFor(src, 'morrowind', 'other')[0].name, 'FromOther.esp');
});

test('loadOrderFor: with no profile chosen, falls back to the game default', () => {
  const src = withOrder(
    { pm: [{ name: 'FromDefault.esp' }] },
    { pm: { gameId: 'morrowind', lastActivated: 9 }, other: { gameId: 'morrowind', lastActivated: 1 } });
  assert.strictEqual(loadOrderFor(src, 'morrowind', '__all__')[0].name, 'FromDefault.esp');
});

test('loadOrderFor: a game Vortex recorded nothing for yields an empty list', () => {
  assert.deepStrictEqual(loadOrderFor(withOrder({}), 'morrowind', '__all__'), []);
  assert.deepStrictEqual(loadOrderFor(withOrder({ pm: 'not an array' }), 'morrowind', '__all__'), []);
});

test('loadOrderFor: an MO2 file has no plugin order at all', () => {
  assert.deepStrictEqual(loadOrderFor({ type: 'mo2', entries: [{ name: 'A' }] }, null, null), []);
  assert.deepStrictEqual(loadOrderFor(null, null, null), []);
});

test('gamesWithLoadOrder: lists only games that actually have one', () => {
  const src = {
    type: 'vortex',
    mods: { morrowind: { a: {} }, skyrimse: { b: {} } },
    profiles: { pm: { gameId: 'morrowind', lastActivated: 9 }, ps: { gameId: 'skyrimse', lastActivated: 9 } },
    loadOrder: { pm: [{ name: 'Morrowind.esm' }] },
  };
  assert.deepStrictEqual(gamesWithLoadOrder(src), ['morrowind']);
});

test('loadOrderNote: explains the gap belongs to Vortex, not to the file', () => {
  const note = loadOrderNote('skyrimse', []);
  assert.match(note, /skyrimse/);
  assert.match(note, /extension/);
});

test('loadOrderNote: names the games that do have one, excluding this one', () => {
  const note = loadOrderNote('skyrimse', ['morrowind', 'oblivionremastered', 'skyrimse']);
  assert.match(note, /morrowind and oblivionremastered/);
  // The game being asked about must not be listed as an alternative to itself.
  assert.ok(!/for morrowind, oblivionremastered and skyrimse/.test(note));
});

test('loadOrderNote: says nothing extra when no game in the file has one', () => {
  assert.ok(!/In this file/.test(loadOrderNote('skyrimse', [])));
});

// ------------------------------------------------------------ install date

test('installedAt: parses the ISO string Vortex writes', () => {
  assert.strictEqual(installedAt('2024-03-20T01:06:42.075Z'), Date.parse('2024-03-20T01:06:42.075Z'));
});

test('installedAt: anything unparseable is null, not NaN or 0', () => {
  // A NaN would sort unpredictably; a 0 would claim the mod was installed in 1970.
  for (const bad of [undefined, null, '', 'not a date', 42, {}]) {
    assert.strictEqual(installedAt(bad), null, 'failed for ' + String(bad));
  }
});

test('installedLabel: shows the date only', () => {
  const ms = new Date(2024, 2, 20, 13, 45).getTime();
  assert.strictEqual(installedLabel(ms), '2024-03-20');
});

test('installedLabel: pads single-digit months and days', () => {
  assert.strictEqual(installedLabel(new Date(2025, 0, 5).getTime()), '2025-01-05');
});

test('installedLabel: no date renders as a dash', () => {
  for (const bad of [null, undefined, NaN, Infinity, '2024-01-01']) {
    assert.strictEqual(installedLabel(bad), '—', 'failed for ' + String(bad));
  }
});

test('viewState: sorts newest installed first, undated last', () => {
  const rows = [
    V('old', { installed: Date.parse('2024-01-01') }),
    V('new', { installed: Date.parse('2026-01-01') }),
    V('never'),
  ];
  assert.deepStrictEqual(
    viewState(rows, { sort: 'installed' }).rows.map((r) => r.modId),
    ['new', 'old', 'never']);
});

test('viewState: the installed sort falls back when nothing has a date', () => {
  const v = viewState([V('A'), V('B')], { sort: 'installed' });
  assert.strictEqual(v.sort, 'name');
  assert.strictEqual(v.hasWhen, false);
});

// ------------------------------------------------------ same Nexus page

test('nexusPageCounts: several files from one page all report the group size', () => {
  // Normal: a mod page ships a main file plus optional patches.
  const counts = nexusPageCounts({
    a: { attributes: { source: 'nexus', modId: 75851 } },
    b: { attributes: { source: 'nexus', modId: 75851 } },
    c: { attributes: { source: 'nexus', modId: 999 } },
  });
  assert.strictEqual(counts.get('a'), 2);
  assert.strictEqual(counts.get('b'), 2);
  assert.strictEqual(counts.get('c'), 1);
});

test('nexusPageCounts: a numeric and string modId are the same page', () => {
  const counts = nexusPageCounts({
    a: { attributes: { source: 'nexus', modId: 12 } },
    b: { attributes: { source: 'nexus', modId: '12' } },
  });
  assert.strictEqual(counts.get('a'), 2);
});

test('nexusPageCounts: non-Nexus mods are not counted at all', () => {
  const counts = nexusPageCounts({
    local1: { attributes: { name: 'Merged Patch' } },
    local2: { attributes: { name: 'Another' } },
  });
  assert.strictEqual(counts.size, 0);
});

test('nexusPageCounts: a nexus mod with no modId is not grouped', () => {
  assert.strictEqual(nexusPageCounts({ a: { attributes: { source: 'nexus' } } }).size, 0);
});

test('buildRows: carries the install date and the page group size', () => {
  const rows = buildRows(vortex({
    a: { attributes: { name: 'A', source: 'nexus', modId: 5, installTime: '2025-06-01T10:00:00Z' } },
    b: { attributes: { name: 'B', source: 'nexus', modId: 5 } },
    c: { attributes: { name: 'C' } },
  }), 'skyrimse', '__all__');
  const by = Object.fromEntries(rows.map((r) => [r.name, r]));
  assert.strictEqual(by.A.installed, Date.parse('2025-06-01T10:00:00Z'));
  assert.strictEqual(by.B.installed, null);
  assert.strictEqual(by.A.pageSiblings, 2, 'A and B share a page');
  assert.strictEqual(by.C.pageSiblings, 0, 'a local mod has no page');
});

// --------------------------------------------- column presence / csv status

test('columnsIn: reports only the columns the rows actually carry', () => {
  // An MO2 row set: an order, and nothing else optional.
  const mo2 = [{ name: 'A', order: 1 }];
  assert.deepStrictEqual(columnsIn(mo2),
    { order: true, size: false, coll: false, endo: false, when: false });
});

test('columnsIn: one row carrying a field is enough to show the column', () => {
  const rows = [{ name: 'A' }, { name: 'B', size: 10 }];
  assert.strictEqual(columnsIn(rows).size, true);
});

test('columnsIn: an endorsement decision of any kind counts, including Abstained', () => {
  assert.strictEqual(columnsIn([{ endorsed: 'Abstained' }]).endo, true);
  assert.strictEqual(columnsIn([{ endorsed: undefined }]).endo, false);
  assert.strictEqual(columnsIn([{ endorsed: null }]).endo, false);
});

test('columnsIn: an empty or missing row set carries no columns', () => {
  const none = { order: false, size: false, coll: false, endo: false, when: false };
  assert.deepStrictEqual(columnsIn([]), none);
  assert.deepStrictEqual(columnsIn(null), none);
});

test('columnsIn: the view and the exports agree about the same rows', () => {
  // The whole point of the helper -- viewState decides the table's columns,
  // and the exports have to reach the same answer or a column appears in a
  // file that was not in the view it came from.
  const rows = [V('A', { size: 10 }), V('B', { endorsed: 'Undecided' })];
  const view = viewState(rows, {});
  const cols = columnsIn(rows);
  assert.deepStrictEqual(
    { order: view.hasOrder, size: view.hasSize, coll: view.hasColl, endo: view.hasEndo,
      when: view.hasWhen },
    cols);
});

test('csvStatus: an unknown state is blank, not the em dash the table shows', () => {
  assert.strictEqual(csvStatus(true), 'enabled');
  assert.strictEqual(csvStatus(false), 'disabled');
  assert.strictEqual(csvStatus(null), '');
  assert.strictEqual(csvStatus(undefined), '');
  // The table shows the same unknown state as an em dash; a sheet gets a blank.
  assert.strictEqual(statusLabel(null), '—');
});

// --------------------------------------------------------- all-games export

const multi = (games, profiles) => ({ type: 'vortex', mods: games, profiles: profiles || {} });

test('gamesWithMods: skips games with no mods in them', () => {
  const src = multi({ full: { a: { attributes: {} } }, empty: {} });
  assert.deepStrictEqual(gamesWithMods(src), ['full']);
});

test('gamesWithMods: an MO2 file has no games to enumerate', () => {
  assert.deepStrictEqual(gamesWithMods({ type: 'mo2', entries: [] }), []);
  assert.deepStrictEqual(gamesWithMods(null), []);
});

test('defaultProfileFor: picks the most recently activated profile', () => {
  const src = multi({ g: {} }, {
    old: { gameId: 'g', name: 'Old', lastActivated: 1 },
    recent: { gameId: 'g', name: 'Recent', lastActivated: 99 },
    other: { gameId: 'elsewhere', name: 'Other', lastActivated: 100 },
  });
  assert.strictEqual(defaultProfileFor(src, 'g'), 'recent');
});

test('defaultProfileFor: falls back to the full installed list with no profile', () => {
  // One real game has mods but no profile at all; it must still export.
  assert.strictEqual(defaultProfileFor(multi({ g: {} }, {}), 'g'), '__all__');
});

test('allGamesRows: tags every row with its game', () => {
  const src = multi({
    skyrimse: { a: { attributes: { name: 'A' } } },
    morrowind: { b: { attributes: { name: 'B' } }, c: { attributes: { name: 'C' } } },
  });
  const rows = allGamesRows(src, {});
  assert.strictEqual(rows.length, 3);
  assert.strictEqual(rows.filter((r) => !r.game).length, 0);
  const byGame = rows.reduce((acc, r) => { acc[r.game] = (acc[r.game] || 0) + 1; return acc; }, {});
  assert.deepStrictEqual(byGame, { skyrimse: 1, morrowind: 2 });
});

test('allGamesRows: uses each game its own profile for enabled state', () => {
  const src = multi(
    { g1: { m: { attributes: { name: 'One' } } }, g2: { m: { attributes: { name: 'Two' } } } },
    { p1: { gameId: 'g1', modState: { m: { enabled: false } } } });
  const rows = allGamesRows(src, {});
  const by = Object.fromEntries(rows.map((r) => [r.game, r.enabled]));
  assert.strictEqual(by.g1, false, 'g1 has a profile, so status is known');
  assert.strictEqual(by.g2, null, 'g2 has none, so status is unknown');
});

test('allGamesRows: applies the view filters to every game', () => {
  const src = multi(
    { g1: { a: { attributes: { name: 'Water Mod' } }, b: { attributes: { name: 'Other' } } },
      g2: { c: { attributes: { name: 'Water Two' } } } });
  assert.strictEqual(allGamesRows(src, {}).length, 3);
  assert.strictEqual(allGamesRows(src, { search: 'water' }).length, 2);
});

test('allGamesRows: an MO2 file exports nothing here', () => {
  // The all-games export is Vortex-only; modlist.txt is one profile of one game.
  assert.deepStrictEqual(allGamesRows({ type: 'mo2', entries: [{ name: 'A' }] }, {}), []);
});

test('allGamesRows: no games means no rows rather than a throw', () => {
  assert.deepStrictEqual(allGamesRows(multi({}), {}), []);
  assert.deepStrictEqual(allGamesRows(null, {}), []);
});

test('allGamesRows: a game selection narrows the export', () => {
  const src = multi({
    skyrimse: { a: { attributes: { name: 'A' } } },
    morrowind: { b: { attributes: { name: 'B' } } },
    fallout4: { c: { attributes: { name: 'C' } } },
  });
  const rows = allGamesRows(src, { games: ['skyrimse', 'fallout4'] });
  assert.deepStrictEqual(rows.map((r) => r.game), ['skyrimse', 'fallout4']);
});

test('allGamesRows: the selection follows the file order, not the given order', () => {
  // Two exports of the same games have to produce the same sheet, whatever
  // order the boxes happened to be ticked in.
  const src = multi({
    skyrimse: { a: { attributes: { name: 'A' } } },
    morrowind: { b: { attributes: { name: 'B' } } },
  });
  const asked = allGamesRows(src, { games: ['morrowind', 'skyrimse'] });
  assert.deepStrictEqual(asked.map((r) => r.game), ['skyrimse', 'morrowind']);
});

test('allGamesRows: a game named in the selection but absent is skipped', () => {
  const src = multi({ skyrimse: { a: { attributes: { name: 'A' } } } });
  assert.strictEqual(allGamesRows(src, { games: ['skyrimse', 'oblivion'] }).length, 1);
  assert.strictEqual(allGamesRows(src, { games: [] }).length, 0);
});

test('allGamesRows: no selection still means every game', () => {
  const src = multi({
    skyrimse: { a: { attributes: { name: 'A' } } },
    morrowind: { b: { attributes: { name: 'B' } } },
  });
  assert.strictEqual(allGamesRows(src, {}).length, 2);
  assert.strictEqual(allGamesRows(src, { games: null }).length, 2);
});

test('allGamesFileName: a full selection keeps the original name', () => {
  assert.strictEqual(allGamesFileName(['a', 'b'], 2), 'vortex-modlist-all-games.csv');
  assert.strictEqual(allGamesFileName([], 2), 'vortex-modlist-all-games.csv');
});

test('allGamesFileName: a small selection names its games', () => {
  assert.strictEqual(allGamesFileName(['skyrimse'], 3), 'vortex-modlist-skyrimse.csv');
  assert.strictEqual(allGamesFileName(['skyrimse', 'fallout4'], 3),
    'vortex-modlist-skyrimse-fallout4.csv');
});

test('allGamesFileName: more than three games is not a filename', () => {
  assert.strictEqual(allGamesFileName(['a', 'b', 'c', 'd'], 9),
    'vortex-modlist-selected-games.csv');
});

test('allGamesFileName: a game id that is not a plain slug never reaches the name', () => {
  // Game ids come out of the state file, so they are not trusted to be safe
  // path segments.
  assert.strictEqual(allGamesFileName(['../etc/passwd'], 3),
    'vortex-modlist-selected-games.csv');
  assert.strictEqual(allGamesFileName(['ok', 'has space'], 3),
    'vortex-modlist-selected-games.csv');
});

// ------------------------------------------------- markdown / bbcode export

// Both formats are pasted somewhere that renders them, so the escaping tests
// matter more than the layout ones: a mod name is written by a mod author.

test('mdCell: a pipe cannot end the cell', () => {
  assert.strictEqual(mdCell('Widescreen | 21:9'), 'Widescreen \\| 21:9');
});

test('mdCell: markdown syntax characters are escaped, not dropped', () => {
  assert.strictEqual(mdCell('*A* _B_ `C` [D]'), '\\*A\\* \\_B\\_ \\`C\\` \\[D\\]');
});

test('mdCell: a < becomes an entity, since markdown passes raw HTML through', () => {
  // Only the opening angle bracket has to go: nothing can start a tag without
  // one, and a surviving > keeps "1.0 -> 2.0" readable in the raw text.
  assert.strictEqual(mdCell('<img src=x onerror=y>'), '&lt;img src=x onerror=y>');
  assert.strictEqual(mdCell('version 1.0 -> 2.0'), 'version 1.0 -> 2.0');
});

test('mdCell: an existing backslash is escaped before the escapes are added', () => {
  // Otherwise a name ending in a backslash would escape our own separator.
  assert.strictEqual(mdCell('Data\\'), 'Data\\\\');
  assert.strictEqual(mdCell('a\\|b'), 'a\\\\\\|b');
});

test('mdCell: a newline in a name cannot break the row', () => {
  assert.strictEqual(mdCell('Two\nLines'), 'Two Lines');
  assert.strictEqual(mdCell('Two\r\n  Lines'), 'Two Lines');
});

test('mdCell: an ordinary name is left alone', () => {
  assert.strictEqual(mdCell('SkyUI 5.2 SE'), 'SkyUI 5.2 SE');
});

test('mdCell: nothing at all is an empty cell, not "undefined"', () => {
  assert.strictEqual(mdCell(undefined), '');
  assert.strictEqual(mdCell(null), '');
});

test('bbSafe: brackets become parentheses so a name cannot open a tag', () => {
  assert.strictEqual(bbSafe('Skyrim [SE]'), 'Skyrim (SE)');
  assert.strictEqual(bbSafe('[url=http://evil]x[/url]'), '(url=http://evil)x(/url)');
});

test('bbSafe: a newline in a name cannot break the list item', () => {
  assert.strictEqual(bbSafe('Two\nLines'), 'Two Lines');
});

test('bbSafe: an ordinary name is left alone', () => {
  assert.strictEqual(bbSafe('SkyUI 5.2 SE'), 'SkyUI 5.2 SE');
});

test('safeHttpUrl: a real Nexus link passes', () => {
  const u = 'https://www.nexusmods.com/skyrimspecialedition/mods/12604';
  assert.strictEqual(safeHttpUrl(u), u);
});

test('safeHttpUrl: anything that could break out of the link syntax is refused', () => {
  ['http://www.nexusmods.com/x', 'javascript:alert(1)', 'https://a b.com',
   'https://x.com/a)b', 'https://x.com/a]b', 'https://x.com/a"b', "https://x.com/a'b",
   '', null, undefined].forEach((bad) => {
    assert.strictEqual(safeHttpUrl(bad), null, String(bad) + ' should be refused');
  });
});

test('mdLink / bbLink: a link is built only when there is a safe URL', () => {
  const u = 'https://www.nexusmods.com/skyrim/mods/1';
  assert.strictEqual(mdLink('SkyUI', u), '[SkyUI](' + u + ')');
  assert.strictEqual(bbLink('SkyUI', u), '[url=' + u + ']SkyUI[/url]');
  assert.strictEqual(mdLink('SkyUI', null), 'SkyUI');
  assert.strictEqual(bbLink('SkyUI', null), 'SkyUI');
  assert.strictEqual(mdLink('SkyUI', 'javascript:alert(1)'), 'SkyUI');
  assert.strictEqual(bbLink('SkyUI', 'javascript:alert(1)'), 'SkyUI');
});

test('mdLink / bbLink: the name is still escaped inside the link', () => {
  const u = 'https://www.nexusmods.com/skyrim/mods/1';
  assert.strictEqual(mdLink('A]B', u), '[A\\]B](' + u + ')');
  assert.strictEqual(bbLink('A]B', u), '[url=' + u + ']A)B[/url]');
});

test('markdownLines: nothing to export is no table at all', () => {
  assert.deepStrictEqual(markdownLines([]), []);
  assert.deepStrictEqual(markdownLines(null), []);
});

test('markdownLines: columns appear only where the data does', () => {
  assert.deepStrictEqual(markdownLines([V('A')]), [
    '| Mod | Version | Status |',
    '| --- | --- | --- |',
    '| A | 1.0 | enabled |',
  ]);
});

test('markdownLines: size, collection and endorsement columns show up when present', () => {
  const rows = [V('A', { size: 47185920, collectionText: 'CET+Essentials', endorsed: 'Endorsed' })];
  assert.deepStrictEqual(markdownLines(rows), [
    '| Mod | Version | Size | From collection | Endorsed | Status |',
    '| --- | --- | --: | --- | --- | --- |',
    '| A | 1.0 | 45.0 MB | CET+Essentials | yes | enabled |',
  ]);
});

test('markdownLines: the # column carries each row own order, not its position', () => {
  // The table can be sorted by name while still holding MO2 priority numbers.
  // Writing the position instead would silently renumber the load order.
  const out = markdownLines([V('Alpha', { order: 9 }), V('Zeta', { order: 1 })]);
  assert.strictEqual(out[0], '| # | Mod | Version | Status |');
  assert.strictEqual(out[2], '| 9 | Alpha | 1.0 | enabled |');
  assert.strictEqual(out[3], '| 1 | Zeta | 1.0 | enabled |');
});

test('markdownLines: a pipe in a mod name does not add a column', () => {
  const out = markdownLines([V('Widescreen | 21:9', { name: 'Widescreen | 21:9' })]);
  // Split on separators markdown would actually honour: an escaped pipe is not one.
  const cells = (line) => line.split(/(?<!\\)\|/).length;
  assert.strictEqual(cells(out[2]), cells(out[0]));
});

test('markdownLines: the mod name links to its source when there is one', () => {
  const u = 'https://www.nexusmods.com/skyrim/mods/1';
  const out = markdownLines([V('SkyUI', { sourceUrl: u })]);
  assert.strictEqual(out[2], '| [SkyUI](' + u + ') | 1.0 | enabled |');
});

test('markdownLines: unknown status renders as a dash rather than a blank', () => {
  assert.strictEqual(markdownLines([V('A', { enabled: null })])[2], '| A | 1.0 | — |');
});

test('bbcodeLines: nothing to export is no list at all', () => {
  assert.deepStrictEqual(bbcodeLines([]), []);
  assert.deepStrictEqual(bbcodeLines(null), []);
});

test('bbcodeLines: a plain list, with status in parentheses', () => {
  assert.deepStrictEqual(bbcodeLines([V('A'), V('B', { enabled: false })]), [
    '[list]',
    '[*]A — 1.0 (enabled)',
    '[*]B — 1.0 (disabled)',
    '[/list]',
  ]);
});

test('bbcodeLines: the position is written out, not left to list auto-numbering', () => {
  // [list=1] would number by table order, which is not the priority order
  // once the table is sorted by name.
  assert.deepStrictEqual(bbcodeLines([V('Alpha', { order: 9 }), V('Zeta', { order: 1 })]), [
    '[list]',
    '[*]9. Alpha — 1.0 (enabled)',
    '[*]1. Zeta — 1.0 (enabled)',
    '[/list]',
  ]);
});

test('bbcodeLines: an unknown status is left off rather than shown as a dash', () => {
  assert.strictEqual(bbcodeLines([V('A', { enabled: null })])[1], '[*]A — 1.0');
});

test('bbcodeLines: a missing version is left off, and a size is included', () => {
  assert.strictEqual(bbcodeLines([V('A', { version: '—', size: 47185920 })])[1],
    '[*]A — 45.0 MB (enabled)');
});

test('bbcodeLines: a bracketed mod name cannot open a tag', () => {
  const out = bbcodeLines([V('x', { name: 'Skyrim [SE] Patch' })]);
  assert.strictEqual(out[1], '[*]Skyrim (SE) Patch — 1.0 (enabled)');
});

const D = (change, row, changes) => ({ change, row, changes });

test('markdownDiffLines / bbcodeDiffLines: an empty diff exports nothing', () => {
  assert.deepStrictEqual(markdownDiffLines([]), []);
  assert.deepStrictEqual(bbcodeDiffLines(null), []);
});

test('markdownDiffLines: what changed lands in the detail column', () => {
  const diffs = [
    D('added', V('A')),
    D('changed', V('B'), [{ field: 'version', from: '1.0', to: '2.0' }]),
  ];
  assert.deepStrictEqual(markdownDiffLines(diffs), [
    '| Change | Mod | Version | Status | Detail |',
    '| --- | --- | --- | --- | --- |',
    '| added | A | 1.0 | enabled |  |',
    '| changed | B | 1.0 | enabled | version 1.0 -> 2.0 |',
  ]);
});

test('bbcodeDiffLines: the change type is bolded, the detail follows the name', () => {
  const diffs = [
    D('added', V('A')),
    D('changed', V('B'), [{ field: 'version', from: '1.0', to: '2.0' }]),
  ];
  assert.deepStrictEqual(bbcodeDiffLines(diffs), [
    '[list]',
    '[*][b]added[/b] A — enabled',
    '[*][b]changed[/b] B — version 1.0 -> 2.0',
    '[/list]',
  ]);
});

test('diff exports escape a hostile name in both formats', () => {
  const md = markdownDiffLines([D('added', V('x', { name: 'A|B' }))]);
  assert.ok(md[2].indexOf('A\\|B') !== -1, md[2]);
  const bb = bbcodeDiffLines([D('added', V('x', { name: '[b]A[/b]' }))]);
  assert.strictEqual(bb[1], '[*][b]added[/b] (b)A(/b) — enabled');
});

// --------------------------------------------------------------- theming

test('themeIds: the picker offers exactly the themes that have a block', () => {
  assert.deepStrictEqual(themeIds(),
    ['midnight', 'vortex', 'nmm', 'glass', 'uesp', 'green', 'amber', 'cyberpunk']);
});

test('resolveTheme: a known id passes through', () => {
  themeIds().forEach((id) => assert.strictEqual(resolveTheme(id), id));
});

test('resolveTheme: anything unrecognised falls back to the default', () => {
  // What comes out of storage is whatever was last written there, including by
  // an older version of this file. A value with no block behind it would leave
  // the page unstyled rather than merely wrong -- 'nexus' is the theme's own
  // former id, from before it was renamed to 'vortex'.
  ['', 'sepia', 'nexus', 'MIDNIGHT', ' glass', null, undefined, 0, {}].forEach((bad) => {
    assert.strictEqual(resolveTheme(bad), 'midnight', JSON.stringify(bad) + ' should fall back');
  });
});

test('resolveTheme: the renamed terminal themes keep working from storage', () => {
  // These two were named after the games they resemble before being renamed
  // for the colour they actually are. Anyone who had one selected has the old
  // id in their browser, and should not be silently reset to the default.
  assert.strictEqual(resolveTheme('fo3'), 'green');
  assert.strictEqual(resolveTheme('nv'), 'amber');
});

test('legacyThemeId: maps only the two ids that were renamed', () => {
  assert.strictEqual(legacyThemeId('fo3'), 'green');
  assert.strictEqual(legacyThemeId('nv'), 'amber');
  ['midnight', 'green', 'amber', 'cyberpunk', 'nexus', '', null].forEach((v) => {
    assert.strictEqual(legacyThemeId(v), null, String(v) + ' is not a rename');
  });
});

test('themeMeta: every theme declares a colour scheme and a chrome colour', () => {
  themeIds().forEach((id) => {
    const m = themeMeta(id);
    assert.match(m.colorScheme, /^(light|dark)$/, id + ' needs a real color-scheme');
    assert.match(m.themeColor, /^#[0-9a-f]{6}$/, id + ' needs a hex theme-color');
  });
});

test('themeMeta: color-scheme matches whether each theme is actually light or dark', () => {
  // Native checkboxes and the select chevron follow color-scheme, not our
  // variables -- getting this wrong paints a dark checkbox on a white page,
  // or a white one on a dark page. There is no shortcut like "only the light
  // theme is light": NMM is a light theme too, so this has to be a mapping
  // per id rather than one name singled out and everything else assumed dark.
  assert.deepStrictEqual(
    Object.fromEntries(themeIds().map((id) => [id, themeMeta(id).colorScheme])),
    { midnight: 'dark', vortex: 'dark', nmm: 'light', glass: 'light',
      uesp: 'light', green: 'dark', amber: 'dark', cyberpunk: 'dark' }
  );
});

test('themeMeta: an unknown theme gets the default metadata, not undefined', () => {
  assert.deepStrictEqual(themeMeta('nope'), themeMeta('midnight'));
});

// -------------------------------------------------- optional: real backups

const backupDir = process.env.APPDATA
  ? path.join(process.env.APPDATA, 'Vortex', 'temp', 'state_backups_full')
  : null;
const realBackups = backupDir && fs.existsSync(backupDir)
  ? fs.readdirSync(backupDir).filter((f) => f.endsWith('.json')).map((f) => path.join(backupDir, f))
  : [];

test('real Vortex backups on this machine parse and diff', {
  skip: realBackups.length < 2 ? 'needs two local Vortex state backups; none committed to the repo' : false,
}, () => {
  const sources = realBackups.slice(0, 2).map((f) => {
    const res = parseModlist(fs.readFileSync(f, 'utf8'));
    assert.ok(!res.error, 'failed to parse ' + path.basename(f) + ': ' + res.error);
    assert.strictEqual(res.source.type, 'vortex');
    return res.source;
  });

  const games = Object.keys(sources[0].mods);
  assert.ok(games.length > 0, 'expected at least one game in a real backup');

  for (const game of games) {
    const a = buildRows(sources[0], game, '__all__');
    const b = buildRows(sources[1], game, '__all__');
    for (const row of a.concat(b)) {
      assert.ok(typeof row.name === 'string' && row.name.length > 0, 'every row needs a name');
      if (row.sourceUrl) {
        assert.match(row.sourceUrl, /^https:\/\/www\.nexusmods\.com\//, 'links must point at nexusmods.com');
      }
    }
    // Must not throw, and must account for every mod on both sides.
    const d = diffRows(a, b);
    const ids = new Set(a.concat(b).map((r) => r.modId));
    assert.strictEqual(d.length, ids.size);
  }
});
